name = "lapce-vue"
version = "0.0.2"
author = "xiaoxin-sky"
display-name = "vue"
description = "vue auto-complete„ÄÅts type-check"
wasm = "bin/lapce-vue.rustc.wasm"

[activation]
language = ["vue"]
workspace-contains = ["*/Cargo.toml"]

[config."serverPath"]
default = ""
description = "Path to vue-language-server executable. When empty, it points to the bundled binary."
